services:
  node-18:
    build:
      context: ./node-18
      dockerfile: Dockerfile
    image: crpi-a7p27yxlrmekg1a3.cn-beijing.personal.cr.aliyuncs.com/elin-common/node-18:latest
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: crpi-a7p27yxlrmekg1a3.cn-beijing.personal.cr.aliyuncs.com/elin-common/nginx:latest